### ISSUE TITLE
Bot goes down

### ISSUE THREAD

**Issue by kenygamer** [discord-php/DiscordPHP#412] opened 2020-11-11 01:53 UTC
Console logs:

```
2020-11-10T18:12:22.219464+00:00] DiscordPHP.INFO: websocket reconnected to discord [] []
[2020-11-10T19:10:07.299076+00:00] DiscordPHP.WARNING: websocket closed {"op":1006,"reason":"Underlyin
g connection closed"} []
[2020-11-10T19:10:07.299155+00:00] DiscordPHP.WARNING: reconnecting in 2 seconds [] []
[2020-11-10T19:10:09.466410+00:00] DiscordPHP.INFO: starting reconnect {"reconnect_count":15} []
```

**Comment by davidcole1340** [comment] 2020-11-11 20:18
`Underlying connection closed` usually means the connection closed due to uncontrollable factors, the reason it still shows in Discord is that they expect this to happen - it's the internet after all - so your "session" is still active for a couple of minutes. 

Your bot should automatically reconnect, is it not?

**Comment by kenygamer** [comment] 2020-11-11 20:40
> `Underlying connection closed` usually means the connection closed due to uncontrollable factors, the reason it still shows in Discord is that they expect this to happen - it's the internet after all - so your "session" is still active for a couple of minutes.
> 
> Your bot should automatically reconnect, is it not?

It can login fine. But it takes about an hour to work again. I'm suspecting a ratelimiting issue, because I've been blocked already at least three times, an hour each. To reproduce it I've tried sending 50 embeds all followed. If this is true, ratelimiting has an issue.

**Comment by kenygamer** [comment] 2020-11-13 07:29
@davidcole1340 It seems that this is related to the ratelimit issue. Probably, hitting a ratelimit causes all bots to go down and they must be turned on again for them to connect again.  The logs show constant connection close and reconnect attempts.

**Comment by davidcole1340** [comment] 2020-11-14 04:43
- Are you using any blocking code? e.g. any sleep commands that aren't React timers
- Could you check the library version? `composer show | grep team-reflex`

**Comment by kenygamer** [comment] 2020-11-14 15:32
`team-reflex/discord-php       v5.0.11 An unofficial API to interact with the voice and text server...`

**Comment by kenygamer** [comment] 2020-11-14 20:56
I migrated 6 bots to Discord PHP last week, so being ratelimited constantly is significantly delaying my work. I come from Yasmin so I had to migrate because of this issue hapenning there.

**Comment by davidcole1340** [comment] 2020-11-14 21:59
Can you try the `refactor/http` branch? I've been working on the rate-limit stuff. I don't think it will fix it but worth a shot. Just run `composer require team-reflex/discord-php dev-refactor/http`.

Otherwise, join our Discord server in the readme and I can take a look at your code to see if that is the problem.

**Comment by kenygamer** [comment] 2020-11-15 18:25
> Can you try the `refactor/http` branch? I've been working on the rate-limit stuff. I don't think it will fix it but worth a shot. Just run `composer require team-reflex/discord-php dev-refactor/http`.
> 
> Otherwise, join our Discord server in the readme and I can take a look at your code to see if that is the problem.

Much better, thanks for your work!

**Comment by kenygamer** [comment] 2020-11-25 15:56
Reopneing this issue. It seems that the bot down issue got fixed on the ratelimiting part but not on the part that another user recently reported. In fact the bot crashes with the latest commit. I updated my DiscordPHP from a version of a month ago and that's when I started having the problem.

Logs:

```
2020-11-25T12:42:24.539924+00:00] X.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
[2020-11-25T12:42:24.578210+00:00] X.INFO: websocket connection has been created [] []
[2020-11-25T12:42:24.578482+00:00] X.INFO: received hello [] []
[2020-11-25T12:42:24.578710+00:00] X.INFO: heartbeat timer initilized {"interval":41250.0} []
[2020-11-25T12:42:24.578827+00:00] X.INFO: resuming connection {"payload":{"op":6,"d":{"session_id":"X","seq":
583,"token":"X.X7b6Kw.A3LSLaSY3VAuiDL_BpQKHS3HrHI"}}} []
[2020-11-25T12:42:24.599393+00:00] DiscordPHP.INFO: websocket reconnected to discord [] []
```

**Comment by davidcole1340** [comment] 2020-11-27 04:50
Is there any more logs? Can't really do anything without more information since I can't reproduce

**Comment by kenygamer** [comment] 2020-11-27 08:15
> Is there any more logs? Can't really do anything without more information since I can't reproduce
The error happens exceptionally and after updating recently, but it is exactly as the other user pointed out. I will enable debug, but that's all the logs for now. The websocket is reconnecting unless the bot is restarted, and it can spend many hours like this.

**Comment by kenygamer** [comment] 2020-11-29 18:27
1bdf9c3 is not very nice for this issue.

```
PHP Fatal error: Uncaught TypeError: array_search(): Argument #2 ($haystack) must be of type array, null given in /home/bot/vendor/team-reflex/discord-php/src/Disco rd/Parts/Channel/Message.php:235
```

**Comment by davidcole1340** [comment] 2020-12-14 04:44
Have you been able to reproduce? I haven't had problems for over 1 month now.

**Comment by AkmalFairuz** [comment] 2020-12-16 10:32
Same issue

**Comment by kenygamer** [comment] 2020-12-19 07:08
@davidcole1340 Yes, bot just froze again in reconnect. OP Code 7 as far as I recall.

**Comment by kenygamer** [comment] 2020-12-20 16:55
@davidcole1340 I keep receiving numerous complains of bots going down. I can't even restart the frozen bot.

```
stored guilds {"count":0,"unavailable":1} []
[2020-12-20T16:48:42.052817+00:00] DiscordPHP.INFO: all guilds are now available {"count":1} []
[2020-12-20T16:48:42.052917+00:00] DiscordPHP.INFO: set up chunking, checking for chunks every 5 seconds
 [] []
[2020-12-20T16:48:42.052958+00:00] DiscordPHP.INFO: client is ready [] []
```
os

**Comment by key2peace** [comment] 2020-12-20 18:30
how do you try to restart the bot?

**Comment by kenygamer** [comment] 2020-12-20 19:17
> how do you try to restart the bot?

When the bot freezes because of this issue, I must kill the process.

**Comment by kenygamer** [comment] 2020-12-26 22:09
This is critical to fix.

**Comment by davidcole1340** [comment] 2020-12-26 22:32
No one but yourself and Akmel have had any issues, my bot is still running since my last message 13 days ago so almost 2 months of uptime now.

Do you have any code that would block execution? That will likely be it, try to find asynchronous libraries to do the same work. Otherwise, I can't help unless you post some code samples.

**Comment by kenygamer** [comment] 2020-12-26 22:35
@davidcole1340 There is no code that blocks execution, but I do have bots that have been running for a long time too. I host 10+ bots.

The only episode I remember is when I was restarting the bot quickly, this exact issue hapenned.

**Comment by kenygamer** [comment] 2021-01-07 05:47
@davidcole1340 This may be of interest to you:
```
done! Took 2.4738311767578ms [] []
[2021-01-07T05:43:26.493504+00:00] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json","session":{"total":1
000,"remaining":1,"reset_after":31207207,"max_concurrency":1}} []
[2021-01-07T05:43:26.493583+00:00] DiscordPHP.ERROR: exceeded number of reconnects allowed, waiting before attempting reconnect {"total":1000,"remaining":1
,"reset_after":31207207,"max_concurrency":1} []
```

**Comment by kenygamer** [comment] 2021-01-08 01:58
@davidcole1340 Please give this issue the highest priority. I have 3 bots that were blocked by Discord now, for reaching "max reconnect attempts".

**Comment by valzargaming** [comment] 2021-01-08 02:07
I have three bots that run concurrently under the same IP address and have no issues, unable to reproduce. You're going to need to post some logs showing the conditions that trigger the problem you're running into if you expect to get any kind of resolution.

**Comment by kenygamer** [comment] 2021-01-08 03:42
@valzargaming I have 15 bots running under the same account. The logs are only what I sent.

**Comment by valzargaming** [comment] 2021-01-08 21:30
If those are the only logs produced by the bot then the issue is not with the DiscordPHP library, it is your usage of it. It sounds to me like you are abusing the API and are being banned because you're doing too many things you shouldn't be along the same route even if they are across multiple tokens. You'll have to contact Discord for assistance.

**Comment by key2peace** [comment] 2021-01-08 21:51
15 bots under same account? are you talking about 15 shards of the same bot, or are you talking about 15 different bots running on the same account using the same IP for outgoing connections? In case of second, please note that discord utilizes cloudflare, and some limits are enforced on ip base as well (especially authentication and such).

**Comment by kenygamer** [comment] 2021-01-08 22:17
@key2peace @valzargaming It sounds to me that none of these errors should happen and that DiscordPHP should have handling for it. 

There are 15 bots under the same IP on a server with no more than 1/10 of the capacity in use, not heavy at all. The load is less than you think.

Another bot went down for the same issue.  I'm wondering what DiscordPHP does that it surpraises 1,000 reconnects allowed.

**Comment by davidcole1340** [comment] 2021-01-08 23:26
Can you see what happened above this log here:
```
done! Took 2.4738311767578ms [] []
[2021-01-07T05:43:26.493504+00:00] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json","session":{"total":1
000,"remaining":1,"reset_after":31207207,"max_concurrency":1}} []
[2021-01-07T05:43:26.493583+00:00] DiscordPHP.ERROR: exceeded number of reconnects allowed, waiting before attempting reconnect {"total":1000,"remaining":1
,"reset_after":31207207,"max_concurrency":1} []
```

From what you've posted it seems that an error happened and the bot crashed then restarted, as if the bot was going to reconnect it would log telling you. There is logic in DiscordPHP to prevent you reconnecting too much but if the process stops it loses the information required.

**Comment by kenygamer** [comment] 2021-01-09 06:17
@davidcole1340  I do not have the complete log that you mention however I have 3 new logs of 3 bots.

I don't recognize any bot crash, the bot started fine and has only been reconnecting:

```
021-01-09T05:27:59.693760+00:00] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json","session":{"total":1
000,"remaining":887,"reset_after":55630265,"max_concurrency":1}} []
[2021-01-09T05:27:59.693810+00:00] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
[2021-01-09T05:27:59.731333+00:00] DiscordPHP.INFO: websocket connection has been created [] []
[2021-01-09T05:27:59.731445+00:00] DiscordPHP.INFO: received hello [] []
[2021-01-09T05:27:59.731485+00:00] DiscordPHP.INFO: heartbeat timer initilized {"interval":41250.0} []
[2021-01-09T05:27:59.731509+00:00] DiscordPHP.INFO: identifying {"payload":{"op":2,"d":{"token":"Nzk1ODc1MzU4NTcwMzE1Nzc2.X_PusA.KsaO1hePiIIIirL0YR-ObZoCrx
I","properties":{"$os":"Linux","$browser":"DiscordBot (https://github.com/teamreflex/DiscordPHP, v5.1.0)","$device":"DiscordBot (https://github.com/teamref
lex/DiscordPHP, v5.1.0)","$referrer":"https://github.com/teamreflex/DiscordPHP","$referring_domain":"https://github.com/teamreflex/DiscordPHP"},"compress":
true}}} []
[2021-01-09T05:27:59.822361+00:00] DiscordPHP.INFO: did not parse private channels [] []
[2021-01-09T05:27:59.822447+00:00] DiscordPHP.INFO: stored guilds {"count":0,"unavailable":4} []
[2021-01-09T05:27:59.834925+00:00] DiscordPHP.INFO: all guilds are now available {"count":4} []
[2021-01-09T05:27:59.834977+00:00] DiscordPHP.INFO: set up chunking, checking for chunks every 5 seconds [] []
[2021-01-09T05:27:59.834998+00:00] DiscordPHP.INFO: client is ready [] []

ateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json","session":{"total":1
000,"remaining":1000,"reset_after":0,"max_concurrency":1}} []
[2021-01-09T05:30:25.393302+00:00] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
[2021-01-09T05:32:23.252585+00:00] DiscordPHP.ERROR: websocket error {"e":"Connection to tls://gateway.discord.gg:443 timed out after 20 seconds"} [
```

```
ateway retrieved and set {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json","session":{"total":1
000,"remaining":1000,"reset_after":0,"max_concurrency":1}} []
[2021-01-09T05:30:25.393302+00:00] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://gateway.discord.gg/?v=6&encoding=json"} []
[2021-01-09T05:32:23.252585+00:00] DiscordPHP.ERROR: websocket error {"e":"Connection to tls://gateway.discord.gg:443 timed out after 20 seconds"} [
```

```
websocket closed {"op":1000,"reason":""} []
[2021-01-09T05:49:46.311069+00:00] DiscordPHP.WARNING: reconnecting in 2 seconds [] []
[2021-01-09T05:50:32.672566+00:00] DiscordPHP.INFO: starting reconnect {"reconnect_count":1} []
```

The errors are diverse but they point to the same thing.

Half of these logs end up blocking the bot? Then, I have people complaining about why the bot isn't working.  I have to create one each day to replace the one that is broken (because the reset after, for some reason, is set to like 999 years)

**Comment by valzargaming** [comment] 2021-01-09 07:41
Your only op error codes are 1000 or 1006 which means you're missing heartbeats. Review your code for anything that would be blocking the main event loop process.

**Comment by key2peace** [comment] 2021-01-09 08:51
> @key2peace @valzargaming It sounds to me that none of these errors should happen and that DiscordPHP should have handling for it.
> 
> There are 15 bots under the same IP on a server with no more than 1/10 of the capacity in use, not heavy at all. The load is less than you think.
> 
> Another bot went down for the same issue. I'm wondering what DiscordPHP does that it surpraises 1,000 reconnects allowed.

system performance technically, you could run 100's of bots on the same machine, but DISCORD doesn't like a big amount of authentication traffic from the same IP. CloudFlare is intended as DDoS mitigation tool for websites, and a large volume of traffic from the same IP can be considered a (D)DoS attempt by it.

**Comment by kenygamer** [comment] 2021-01-09 16:38
@key2peace My system perfomance is fine, bots are lightweight. The only thing I can confirm is that as @valzargaming says,  there is code that blocks main execution but only for a couple of seconds, what do I do? Shouldn't Discord be able to handle that properly?

Imagine the case of a large bot, which needs a lot of processing? How 2 seconds will not be allowed?

**Comment by key2peace** [comment] 2021-01-09 16:42
very simple, if your execution takes longer and thus blocks the heartbeat from being acknowledged, discord will disconnect you

**Comment by kenygamer** [comment] 2021-01-09 22:43
> very simple, if your execution takes longer and thus blocks the heartbeat from being acknowledged, discord will disconnect you
Do you agree with me that it should be handled? A two second delay cannot cause your bot to get banned...

Is there any way to stop the execution of my routine to send the heartbeat?

**Comment by davidcole1340** [comment] 2021-01-10 01:54
```
[2021-01-09T05:32:23.252585+00:00] DiscordPHP.ERROR: websocket error {"e":"Connection to tls://gateway.discord.gg:443 timed out after 20 seconds"} []
```
This seems like a network issue, could be the root cause?
Make sure that heartbeats are being acknowledged:
```
[2021-01-10T14:48:51.095253+13:00] DiscordPHP.DEBUG: sending heartbeat {"seq":5} []
[2021-01-10T14:48:51.339354+13:00] DiscordPHP.DEBUG: received heartbeat ack {"response_time":243.95108222961426} []
```

> A two second delay cannot cause your bot to get banned...

It wouldn't be 2 seconds, you need to heartbeat every 41.25 seconds (usually) and as long as the heartbeat is received by Discord before the next one is due it won't disconnect you, so really you have 82.5 seconds (but you don't want to push this - nothing should really take longer than one second to do)

> Is there any way to stop the execution of my routine to send the heartbeat?

Depends on what you are trying to do. As said above, if it's going to take a while you really want to look at asynchronous libraries. Have a look at the [ReactPHP website](https://reactphp.org/) - they have a list of packages you can add to your project.

But since the bot has never said it is reconnecting in your logs, I assume there's an error going on - as DiscordPHP will always log before it is going to reconnect:

```
[2021-01-10T14:53:23.478594+13:00] DiscordPHP.WARNING: received opcode 7 for reconnect [] []
[2021-01-10T14:53:23.478681+13:00] DiscordPHP.WARNING: websocket closed {"op":4000,"reason":"gateway redirecting - opcode 7"} []
[2021-01-10T14:53:23.478703+13:00] DiscordPHP.WARNING: reconnecting in 2 seconds [] []
```

If you are saving logs to file make sure you are redirecting stderr as well as stdout

**Comment by kenygamer** [comment] 2021-01-10 02:23
@davidcole1340 I am running a command in shell. It only takes two seconds, so that's definitely not related and could be a DiscordPHP issue directly. The logs I have:

```
the Discord bot token is required
logging in to Discord...
logged in to Discord.
setting up database...
[2021-01-10T02:06:30.837493+00:00] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.d
iscord.gg/?v=6&encoding=json","session":{"total":1000,"remaining":815,"reset_after":14864322,"max_concurr
ency":1}} []
[2021-01-10T02:06:30.839336+00:00] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://ga
teway.discord.gg/?v=6&encoding=json"} []
[2021-01-10T02:06:30.884560+00:00] DiscordPHP.INFO: websocket connection has been created [] []
[2021-01-10T02:06:30.884667+00:00] DiscordPHP.INFO: received hello [] []
[2021-01-10T02:06:30.884708+00:00] DiscordPHP.INFO: heartbeat timer initilized {"interval":41250.0} []
[2021-01-10T02:06:30.884732+00:00] DiscordPHP.INFO: identifying {"payload":{"op":2,"d":{"token":"Nzk2NjIx
MTk5MTQ0Nzc5ODU3.X_alTg.HKxFonXRdM5QJxhpQKtnpyB9_LE","properties":{"$os":"Linux","$browser":"DiscordBot (
https://github.com/teamreflex/DiscordPHP, v5.1.0)","$device":"DiscordBot (https://github.com/teamreflex/D
iscordPHP, v5.1.0)","$referrer":"https://github.com/teamreflex/DiscordPHP","$referring_domain":"https://g
ithub.com/teamreflex/DiscordPHP"},"compress":true}}} []
[2021-01-10T02:06:30.983871+00:00] DiscordPHP.INFO: did not parse private channels [] []
[2021-01-10T02:06:30.983965+00:00] DiscordPHP.INFO: stored guilds {"count":0,"unavailable":1} []
[2021-01-10T02:06:30.994546+00:00] DiscordPHP.INFO: all guilds are now available {"count":1} []
[2021-01-10T02:06:30.998066+00:00] DiscordPHP.INFO: set up chunking, checking for chunks every 5 seconds
[] []
[2021-01-10T02:06:30.998150+00:00] DiscordPHP.INFO: client is ready [] []
[2021-01-10T02:07:48.115830+00:00] DiscordPHP.WARNING: websocket closed {"op":1000,"reason":""} []
[2021-01-10T02:07:48.116116+00:00] DiscordPHP.WARNING: reconnecting in 2 seconds [] []
[2021-01-10T02:08:45.671747+00:00] DiscordPHP.INFO: starting reconnect {"reconnect_count":1} []
[2021-01-10T02:10:17.248966+00:00] DiscordPHP.WARNING: could not retrieve gateway, using default [] []
[2021-01-10T02:10:17.249014+00:00] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.d
iscord.gg/?v=6&encoding=json","session":{"total":1000,"remaining":1000,"reset_after":0,"max_concurrency":
1}} []
[2021-01-10T02:10:17.249042+00:00] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://ga
teway.discord.gg/?v=6&encoding=json"} []
[2021-01-10T02:12:05.152010+00:00] DiscordPHP.ERROR: websocket error {"e":"Connection to tls://gateway.di
scord.gg:443 timed out after 20 seconds"} []
```

My server network is fine. I was under attack a few days ago but this bot was created just now so that must not be related either.

I am currently logging in shell. I keep the same screen open and those are all the errors I have.

Since it's two months waiting, it is also two months in which I must be recreating 2 or 3 bots daily. I want to urge you to find a fix soon since as I told you my script is not running for more than two seconds and it also affected other bots.

For me it is a handling issue like the new bot quarantined ratelimit.

**Comment by valzargaming** [comment] 2021-01-10 04:27
You do realize that the time to respond to a heartbeat is measured in miliseconds, right? It's not either Discord's or DPHP's fault when your bad code takes so long to run that you fail to respond to a heartbeat. Either figure out a way to run it async or don't use your bot to do it. I had the same issue when using cURL and my workaround was to use react's browser so it runs on the event loop. **_If you block the event loop, it's your fault._**

**Comment by kenygamer** [comment] 2021-01-10 07:19
@valzargaming  Friend? Yes, I understand you perfectly, and I take your advice. What is not understood is my point. @davidcole1340  just said that the heartbeat should be sent every 40 seconds and there is a delay of another 40s. I quote his words:

> It wouldn't be 2 seconds, you need to heartbeat every 41.25 seconds (usually) and as long as the heartbeat is received by Discord before the next one is due it won't disconnect you, so really you have 82.5 seconds (but you don't want to push this - nothing should really take longer than one second to do)


My code only takes 2s, so this error shouldn't be happening.

Also, this connection closed issue appeared long before I had to do this heavy execution on the main loop. Without and with this load, the bot should work, as @davidcole1340  says, there is an issue.

**Comment by key2peace** [comment] 2021-01-10 09:23
I actually solved a lot of lag in the code by moving some stuff out of the bots process into a script that runs periodically in cron. got rid of all sleep statements and minimized other stuff that could be blocking the loop. you should do that with all your periodic running stuff that doesn't rely on actual $discord data to perform.

but yes, I have to agree with my colleagues, if your bot goes down, it's your code causing it, if there where many people having the same issues this issue tracker would have been filled top notch already. Sorry dude, we tried to make you understand for a long time that this is NOT a dphp issue. I am going to give up on this 'issue'.

**Comment by kenygamer** [comment] 2021-01-11 03:15
@key2peace I will take your advice, however it is not the answer I wanted. At the end, I would have done what you tell me anyway. But we don't solve the base problem, because a 2 second delay should again not cause the bot to go down.

I will try that and I will communicate the results to you.

**Comment by kenygamer** [comment] 2021-01-14 04:15
@davidcole1340 @valzargaming Using [child-process](https://github.com/reactphp/child-process), I'm having the same issue:

```
process exited with exit code 0
[2021-01-14T02:44:46.576356+00:00] DiscordPHP.WARNING: received opcode 7 for reconnect [] []
[2021-01-14T02:44:46.576538+00:00] DiscordPHP.WARNING: websocket closed {"op":4000,"reason":"gateway redi
recting - opcode 7"} []
[2021-01-14T02:44:46.577083+00:00] DiscordPHP.WARNING: reconnecting in 2 seconds [] []
[2021-01-14T02:44:48.577367+00:00] DiscordPHP.INFO: starting reconnect {"reconnect_count":1} []
[2021-01-14T02:44:48.662787+00:00] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.d
iscord.gg/?v=6&encoding=json","session":{"total":1000,"remaining":961,"reset_after":68605660,"max_concurr
ency":1}} []
[2021-01-14T02:44:48.663058+00:00] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://ga
teway.discord.gg/?v=6&encoding=json"} []
[2021-01-14T02:44:48.756296+00:00] DiscordPHP.INFO: websocket connection has been created [] []
[2021-01-14T02:44:48.756639+00:00] DiscordPHP.INFO: received hello [] []
[2021-01-14T02:44:48.756776+00:00] DiscordPHP.INFO: heartbeat timer initilized {"interval":41250.0} []
[2021-01-14T02:44:48.756925+00:00] DiscordPHP.INFO: resuming connection {"payload":{"op":6,"d":{"session_
id":"858f75edcb988d05bf24fbb5247f40a5","seq":249,"token":""}}} []
[2021-01-14T02:44:48.777585+00:00] DiscordPHP.INFO: websocket reconnected to discord [] []
[2021-01-14T03:56:22.623726+00:00] DiscordPHP.WARNING: received opcode 7 for reconnect [] []
[2021-01-14T03:56:22.623999+00:00] DiscordPHP.WARNING: websocket closed {"op":4000,"reason":"gateway redi
recting - opcode 7"} []
[2021-01-14T03:56:22.624059+00:00] DiscordPHP.WARNING: reconnecting in 2 seconds [] []
[2021-01-14T03:56:24.624281+00:00] DiscordPHP.INFO: starting reconnect {"reconnect_count":2} []
[2021-01-14T03:56:24.700591+00:00] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.d
iscord.gg/?v=6&encoding=json","session":{"total":1000,"remaining":961,"reset_after":64309626,"max_concurr
ency":1}} []
[2021-01-14T03:56:24.700801+00:00] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://ga
teway.discord.gg/?v=6&encoding=json"} []
[2021-01-14T03:56:24.737738+00:00] DiscordPHP.INFO: websocket connection has been created [] []
[2021-01-14T03:56:24.738116+00:00] DiscordPHP.INFO: received hello [] []
[2021-01-14T03:56:24.738331+00:00] DiscordPHP.INFO: heartbeat timer initilized {"interval":41250.0} []
[2021-01-14T03:56:24.738467+00:00] DiscordPHP.INFO: resuming connection {"payload":{"op":6,"d":{"session_
id":"858f75edcb988d05bf24fbb5247f40a5","seq":392,"token":"."}}} []
[2021-01-14T03:56:24.757019+00:00] DiscordPHP.INFO: websocket reconnected to discord [] []
```

With this library you actually start a new process. The code in the child process takes 5 seconds to run, and runs once every like 30 minutes. That being said, there is nothing that is blocking the bot process.

**Comment by davidcole1340** [comment] 2021-01-14 08:30
This is normal, the disconnections are over 1 hour apart and are triggered by Discord.

**Comment by kenygamer** [comment] 2021-01-14 16:47
@davidcole1340 However, the issue persists when the bot process delays, and I have NO idea why my dear @valzargaming  just labeled this as "invalid". I'm not the only one having this issue. From what I saw, following the advice of @key2peace worked, but I don't admit it to close the issue. DiscordPHP is simply unable to tolerate a delay of 5s, so why, @valzargaming? I don't understand the intention.

**Comment by davidcole1340** [comment] 2021-01-14 21:25
Who else is having this issue? There was one other guy that posted with two words "Same issue" and has said nothing since.
The log you provided made it pretty clear that it is a network issue. The websocket disconnects, fails to retrieve the gateway from Discord and then times out while reconnecting. You even said above that "I was under attack a few days ago".
And you still haven't said what you are actually doing, so all I can do to reproduce is put `sleep(10)` and test, which works fine.

**Comment by kenygamer** [comment] 2021-01-15 06:05
> Who else is having this issue? There was one other guy that posted with two words "Same issue" and has said nothing since.
> The log you provided made it pretty clear that it is a network issue. The websocket disconnects, fails to retrieve the gateway from Discord and then times out while reconnecting. You even said above that "I was under attack a few days ago".
> And you still haven't said what you are actually doing, so all I can do to reproduce is put `sleep(10)` and test, which works fine.

I already ruled out that this had to do with a network problem, otherwise I would have closed my issue.

I was able to reproduce it using persistently `sleep()`, but I don't have time to test now. I have been willing to open issues, so I was hoping someone helps - again, if it had been something that simple, I would have closed this issue.

**Comment by key2peace** [comment] 2021-01-15 07:08
very simple, if you ask too much from the bot or discord, it punches you in the face for it. i have HAD the issue before, and it turned out to be some blocking stuff in my code, moved it out of the bot into an external script, and voila, no more issues.

**Comment by key2peace** [comment] 2021-01-15 15:29
too much related to #470 which has been requested to be closed by submitter, closing this one as well

**Comment by kenygamer** [comment] 2021-01-21 04:17
@davidcole1340 @key2peace Please reopen the issue, it is back. I don't have any load on the process bot anymore. Everything is being done with [reactphp@child-process](https://github.com/reactphp/child-process)

```
DiscordPHP.ERROR: exceeded number of reconnects allowed, waiting befor
e attempting reconnect {"total":1000,"remaining":1,"reset_after":71114761,"max_concurrency":1} []
```

Reset after 823 days.   A bit crazy.

**Comment by davidcole1340** [comment] 2021-01-21 05:44
I need more information, I still haven't been able to reproduce. The `reset_after` parameter is in milliseconds as well, so it's about 20 hours. You get 24 hours max.

**Comment by kenygamer** [comment] 2021-01-21 07:46
@davidcole1340 David, same  issue replicating in another bot. I really demand an answer.

**Comment by kenygamer** [comment] 2021-01-21 07:47
My bot always shows a significantly lower remaining reconnects count.

**Comment by kenygamer** [comment] 2021-01-21 07:52
David, Does it have something to do with how much I restart the bot? Because I do, I work on large bots of thousands of lines of code.

**Comment by key2peace** [comment] 2021-01-21 15:21
first: you havve no right to demand anything, be glad we attempt to assist, even with the very minimal information you provide.
second: you do know github has those three dots at the end where you can select 'Edit'? Please utilize it.
also, yes,, restarting your bot counts as a reconnect (duh), and session limits could be GLOBAL and ip bound.

**Comment by kenygamer** [comment] 2021-01-21 15:51
@key2peace 

> first: you have no right to demand anything, be glad we attempt to assist, even with the very minimal information you provide.

I didn't want it to have that interpretation. I appreciate the assistsnce, but I have been dealing. with this issue for two months. It is unreliable. I can't go on vacation in peace since my clients message me everyday because their bots are breaking.

> second: you do know github has those three dots at the end where you can select 'Edit'? Please utilize it.

I was up until 5 am answering complaints about this, I had to leave, I do it 90% of the time.

> also, yes,, restarting your bot counts as a reconnect (duh), and session limits could be GLOBAL and ip bound.

Good to know. Is there any way then to prevent that? 

**Affix:**

```
 done! Took 24.947166442871ms [] []
[2021-01-21T15:38:23.505331+00:00] DiscordPHP.WARNING: could not retrieve gateway, using default [] []
[2021-01-21T15:38:23.505664+00:00] DiscordPHP.INFO: gateway retrieved and set {"gateway":"wss://gateway.d
iscord.gg/?v=6&encoding=json","session":{"total":1000,"remaining":1000,"reset_after":0,"max_concurrency":
1}} []
[2021-01-21T15:38:23.506029+00:00] DiscordPHP.INFO: starting connection to websocket {"gateway":"wss://ga
teway.discord.gg/?v=6&encoding=json"} []
[2021-01-21T15:38:23.572736+00:00] DiscordPHP.INFO: websocket connection has been created [] []
[2021-01-21T15:38:23.573748+00:00] DiscordPHP.INFO: received hello [] []
[2021-01-21T15:38:23.574033+00:00] DiscordPHP.INFO: heartbeat timer initilized {"interval":41250.0} []
[2021-01-21T15:38:23.574215+00:00] DiscordPHP.INFO: identifying {"payload":{"op":2,"d":{"token":,"properties":{"$os":"Linux","$browser":"DiscordBot (
https://github.com/teamreflex/DiscordPHP, v5.1.0)","$device":"DiscordBot (https://github.com/teamreflex/D
iscordPHP, v5.1.0)","$referrer":"https://github.com/teamreflex/DiscordPHP","$referring_domain":"https://g
ithub.com/teamreflex/DiscordPHP"},"compress":true}}} []
[2021-01-21T15:38:23.605146+00:00] DiscordPHP.WARNING: websocket closed {"op":4004,"reason":"Authenticati
on failed."} []
[2021-01-21T15:38:23.605483+00:00] DiscordPHP.ERROR: not reconnecting - critical op code {"op":4004,"reas
on":"Authentication failed."} []
```

This happened recently, and I did nothing to make it happen. The bot was running for a couple of hours before it was again blocked. I must make a new one, as always, because I can't have people waiting 24 hours.

This is also a clear sign that there is something wrong with DiscordPHP.

**Comment by key2peace** [comment] 2021-01-21 15:58
yes, you probably authed too often, you probably also got a DM from clyde telling you that your token has been reset, furthermore, why are you like the only one when we know dphp is being used by many that do NOT have this issue? My bot behaves nice and doesn't have ANY of the issues you have.

As I said many many times before, your issue is with discord itself and the way you utilize the bot, and again, I have to tell you to contact discord and ask them why your bot is being so heavily ratelimited. Now do me a favour and file that ticket, coz we are kinda at the end of abilities to help you.

**Closed** 2021-01-28 09:51 UTC
Labels: need more information
