### ISSUE TITLE
Bot stops being able to send messages after some time

### ISSUE THREAD

**Issue by GavChap** [discord-php/DiscordPHP#559] opened 2021-07-22 21:46 UTC
**Environment**
- PHP Version:
    - 8.0.8
- DiscordPHP Version:
    - v6.0.1

**Describe the bug**
After around 1 hour, the bot stops being able to send DM messages, despite being able to receive messages.

**To Reproduce**
Steps to reproduce the behavior: (Assume all classes are added as use << classname >>)
```php
$discord = new Discord(['token' => null // NOTE: I redacted token]);

$discord->on(
    Event::MESSAGE_CREATE,
    function (Message $message, Discord $discord) {

        if ($message->channel->type !== Channel::TYPE_TEXT
            || strtolower($message->content) !== '!testbotcommand') {
            return;
        }

        $message->user->sendMessage(
            "A message"
        )->otherwise(
            function (\Exception $e) {
                $this->logger->info("Message unsendable");
            }
        );
    }
);
```

**Expected behavior**
Bot should still be able to send messages to the message originating user.

**PHP Log**
```2021-07-22T21:25:59.575260+00:00] DiscordPHP.DEBUG: BUCKET postchannels/867350789822611487/messages queued REQ POST channels/867350789822611487/messages [] []
[2021-07-22T21:26:12.944902+00:00] DiscordPHP.DEBUG: resetting payload count {"count":1} []
[2021-07-22T21:26:13.448769+00:00] DiscordPHP.DEBUG: sending heartbeat {"seq":2623} []
[2021-07-22T21:26:13.553866+00:00] DiscordPHP.DEBUG: received heartbeat ack {"response_time":104.98404502868652} []
[2021-07-22T21:26:36.073378+00:00] DiscordPHP.DEBUG: BUCKET getoauth2/applications/@me queued REQ GET oauth2/applications/@me [] []
```

The first line shows the message send command being given, but it never does the next message acknowledging the message has been sent to the server, e.g.

```
[2021-07-23T09:24:06.975308+00:00] DiscordPHP.DEBUG: REQ POST channels/867350789822611487/messages successful [] []
```

**Additional context**
Using Symfony 4.4 framework.

Composer packages:
```
composer/package-versions-deprecated 1.11.99.2 Composer plugin that provides efficient querying for installed package versions (no runtime IO)
discord-php/http                     v8.1.2    Handles HTTP requests to Discord servers
doctrine/annotations                 1.13.1    Docblock Annotations Parser
doctrine/cache                       2.0.3     PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/collections                 1.6.7     PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                      3.1.2     PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, proxies and much...
doctrine/dbal                        2.13.2    Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/deprecations                v0.5.3    A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selectively for packages.
doctrine/doctrine-bundle             2.4.2     Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle  3.1.1     Symfony DoctrineMigrationsBundle
doctrine/event-manager               1.1.1     The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                   2.0.3     PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/instantiator                1.4.0     A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       1.2.1     PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  3.2.0     PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily deploying ch...
doctrine/orm                         2.9.3     Object-Relational-Mapper for PHP
doctrine/persistence                 2.2.1     The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/sql-formatter               1.1.1     a PHP SQL highlighting library
evenement/evenement                  v3.0.1    Événement is a very simple event dispatching library for PHP
friendsofphp/proxy-manager-lts       v1.0.5    Adding support for a wider range of PHP versions to ocramius/proxy-manager
guzzlehttp/guzzle                    7.3.0     Guzzle is a PHP HTTP client library
guzzlehttp/promises                  1.4.1     Guzzle promises library
guzzlehttp/psr7                      1.8.2     PSR-7 message implementation that also provides common utility methods
laminas/laminas-code                 4.4.2     Extensions to the PHP Reflection API, static code scanning, and code generation
mollie/polyfill-libsodium            v1.1.1    A polyfill package to transition from the libsodium php extension to the sodium extension. Which is included in PHP 7.2
monolog/monolog                      2.3.0     Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/jmespath.php               2.6.1     Declaratively specify how to extract elements from a JSON document
nesbot/carbon                        2.50.0    An API extension for DateTime that supports 281 different languages.
nikic/php-parser                     v4.11.0   A PHP parser written in PHP
psr/cache                            2.0.0     Common interface for caching libraries
psr/container                        1.1.1     Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                 1.0.0     Standard interfaces for event handling.
psr/http-client                      1.0.1     Common interface for HTTP clients
psr/http-message                     1.0.1     Common interface for HTTP messages
psr/log                              1.1.4     Common interface for logging libraries
ralouphie/getallheaders              3.0.3     A polyfill for getallheaders.
ratchet/pawl                         v0.3.5    Asynchronous WebSocket client
ratchet/rfc6455                      v0.3      RFC6455 WebSocket protocol handler
react/cache                          v1.1.1    Async, Promise-based cache interface for ReactPHP
react/child-process                  v0.6.3    Event-driven library for executing child processes with ReactPHP.
react/datagram                       v1.5.0    Event-driven UDP datagram socket client and server for ReactPHP
react/dns                            v1.8.0    Async DNS resolver for ReactPHP
react/event-loop                     v1.2.0    ReactPHP's core reactor event loop that libraries can use for evented I/O.
react/http                           v1.4.0    Event-driven, streaming HTTP client and server implementation for ReactPHP
react/partial                        v3.0.0    Partial function application.
react/promise                        v2.8.0    A lightweight implementation of CommonJS Promises/A for PHP
react/promise-stream                 v1.2.0    The missing link between Promise-land and Stream-land for ReactPHP
react/promise-timer                  v1.7.0    A trivial implementation of timeouts for Promises, built on top of ReactPHP.
react/socket                         v1.8.0    Async, streaming plaintext TCP/IP and secure TLS socket server and client connections for ReactPHP
react/stream                         v1.2.0    Event-driven readable and writable streams for non-blocking I/O in ReactPHP
ringcentral/psr7                     1.3.0     PSR-7 message implementation
symfony/cache                        v5.3.3    Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts              v2.4.0    Generic abstractions related to caching
symfony/config                       v5.3.3    Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                      v5.3.2    Eases the creation of beautiful and testable command line interfaces
symfony/dependency-injection         v5.3.3    Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts        v2.4.0    A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge              v5.3.3    Provides integration for Doctrine with various Symfony components
symfony/dotenv                       v5.3.0    Registers environment variables from a .env file
symfony/error-handler                v5.3.3    Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher             v5.3.0    Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts   v2.4.0    Generic abstractions related to dispatching event
symfony/filesystem                   v5.3.3    Provides basic utilities for the filesystem
symfony/finder                       v5.3.0    Finds files and directories via an intuitive fluent interface
symfony/flex                         v1.13.3   Composer plugin for Symfony
symfony/framework-bundle             v5.3.3    Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client-contracts        v2.4.0    Generic abstractions related to HTTP clients
symfony/http-foundation              v5.3.3    Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                  v5.3.3    Provides a structured process for converting a Request into a Response
symfony/maker-bundle                 v1.33.0   Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/options-resolver             v5.3.0    Provides an improved replacement for the array_replace PHP function
symfony/polyfill-intl-grapheme       v1.23.0   Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer     v1.23.0   Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring            v1.23.0   Symfony polyfill for the Mbstring extension
symfony/polyfill-php73               v1.23.0   Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80               v1.23.0   Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81               v1.23.0   Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/proxy-manager-bridge         v5.3.0    Provides integration for ProxyManager with various Symfony components
symfony/routing                      v5.3.0    Maps an HTTP request to a set of configuration variables
symfony/runtime                      v5.3.3    Enables decoupling PHP applications from global state
symfony/service-contracts            v2.4.0    Generic abstractions related to writing services
symfony/stopwatch                    v5.3.0    Provides a way to profile code
symfony/string                       v5.3.3    Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                  v5.3.3    Provides tools to internationalize your application
symfony/translation-contracts        v2.4.0    Generic abstractions related to translation
symfony/var-dumper                   v5.3.3    Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter                 v5.3.3    Allows exporting any serializable PHP data structure to plain PHP code
symfony/yaml                         v5.3.3    Loads and dumps YAML files
team-reflex/discord-php              v6.0.1    An unofficial API to interact with the voice and text service Discord.
trafficcophp/bytebuffer              v0.3      Node.js inspired byte stream buffer for PHP.
```

**Comment by GavChap** [comment] 2021-07-22 21:50
Hosting is on an linux ARM VPS if that makes any difference.

**Comment by davidcole1340** [comment] 2021-07-24 11:47
Will try to take a better look at this as it seems a few people have this issue, I haven't been able to reproduce it so far however so we will see how it goes.

**Comment by davidcole1340** [comment] 2021-07-24 12:03
I've added some more debugging lines to the HTTP package - can you please update the HTTP package using the steps below, try and reproduce the error and then send me the full logfiles? You can PM them to me if you'd like.

To update the HTTP package, add the following line to your `composer.json` file under the `require` section - `"discord-php/http": "v8.x-dev as 8"`.

It should look similar to this:

```json
{
    "require": {
        "team-reflex/discord-php": "^6",
        "discord-php/http": "v8.x-dev as 8"
    }
}
```

**Comment by Woet** [comment] 2021-07-30 05:39
I've added some additional debug to the Bucket.php file:
https://gist.github.com/Woet/7b956c745edbd407c053ca6f7fda8b62

And i'm able to reproduce this by causing an exception:
https://gist.githubusercontent.com/Woet/baf4f5490e44cf7aed812267ce720740/raw/1bce431c535321095825a923f03af33c7f1c02b8/gistfile1.txt

Looks like the exceptions aren't always caught causing `checkerRunning` to get stuck on `true`.

**Comment by GavChap** [comment] 2021-07-30 09:30
I've been unable to look at this due to work, but I'll have a look when I get time over the weekend to see if I can repro this with debugging.

**Comment by Woet** [comment] 2021-07-31 13:56
Should be resolved with the latest commit on the dev branch.

**Closed** 2021-08-02 14:46 UTC
Labels: bug

**Comment by Woet** [comment] 2021-09-17 07:12
Would it be possible to push a new release in DiscordPHP-Http?
